spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: discovery-server

